[workspace]
members = [
    "groups_relay",
    "websocket_builder",
]
optional-members = [
    "load_tester"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
futures-util = "0.3.31"
tokio = { version = "1.38.1", features = ["full"] }
anyhow = { version = "1.0.89", features = ["backtrace"] }
async-trait = "0.1.82"
tracing = { version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
futures = "0.3.31"
clap = { version = "4.5.17", features = ["derive"] }
nostr-sdk = { version = "0.39.0", features = ["all-nips"] }
nostr = { version = "0.39.0", features = ["std"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
rand = "0.8.5"
tokio-tungstenite = "0.24.0"
