#AUTH_URL=ws://localhost:8080 docker compose -f compose.prod.example.yml up
services:
  groups_relay:
    image: ghcr.io/verse-pbc/groups_relay:latest
    platform: linux/amd64
    volumes:
      - ./config:/app/config:ro
    environment:
      RUST_LOG: "${RUST_LOG:-info}"
      NIP29__relay__relay_url: "${RELAY_URL:-ws://strfry:7777}"
      NIP29__relay__auth_url: "${AUTH_URL}" # ws://communities.nos.relay
    ports:
      - "8080:8080"
    depends_on:
      - strfry

  strfry:
    image: ghcr.io/hoytech/strfry:latest
    platform: linux/amd64
    volumes:
      - ./strfry-db:/strfry/data
      - ./config/strfry.conf:/etc/strfry.conf:ro
    ports:
      - "7777:7777"
    command: ./strfry relay --config /etc/strfry.conf

volumes:
  strfry-data: