services:
  groups_relay:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: "info"
      NIP29__relay__relay_url: "ws://strfry:7777"
      NIP29__relay__auth_url: "${AUTH_URL}"
    ports:
      - "8080:8080"
    depends_on:
      - strfry

  strfry:
    image: ghcr.io/hoytech/strfry@sha256:0fc68c78ae31cc6194fbd98ad5cdef6516de4f65b768d4b7250b3cac2b0b3ac8
    volumes:
      - ./strfry-db:/strfry/data
      - ./config/strfry.conf:/etc/strfry.conf:ro
    ports:
      - "7777:7777"
    command: ./strfry relay --config /etc/strfry.conf

volumes:
  strfry-data: