services:
  groups_relay:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./config:/app/config:ro
      - ./config/ndb:/app/config/ndb
    environment:
      RUST_LOG: "${RUST_LOG:-info}"
      NIP29__relay__relay_url: "${RELAY_URL:-ws://strfry:7777}"
      NIP29__relay__auth_url: "${AUTH_URL:-ws://localhost:8080}"
    ports:
      - "8080:8080"

volumes:
  strfry-data:
