name: Rust

on:
  workflow_call:
    outputs:
      success:
        description: "Whether the build and tests succeeded"
        value: ${{ jobs.test.outputs.success }}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set-output.outputs.success }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --workspace --verbose

      - name: Run tests
        run: cargo test --workspace --verbose -- --nocapture

      - name: Set success output
        id: set-output
        run: echo "success=true" >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: |
            target/release/groups_relay
            config/
